modules:
  - app/android-app
  - app/ios-app
  - app/ios-platform
  - app/perf-android
  - app/perf-ios
  - app/shared
  - app/shared-ui
  - app/web-app
  - core
  - server
  - third_party/sqldelight-kotlin-toolchain/sqldelight

plugins:
  - ./third_party/sqldelight-kotlin-toolchain/sqldelight
