#!/usr/bin/env bash
set -euo pipefail

# Apply a locally generated icon variant to all platform directories.
# Usage: ./scripts/apply-icon-variant.sh [dev|beta|ga]
#
# Reads SHILLING_ICON_VARIANT env var if no argument given (default: dev).
# Generated outputs are gitignored, so fresh clones must run
# ./scripts/generate-icons.sh before applying a variant.

cd "$(dirname "$0")/.."

VARIANT="${1:-${SHILLING_ICON_VARIANT:-dev}}"

if [[ ! "$VARIANT" =~ ^(dev|beta|ga)$ ]]; then
  echo "Error: variant must be dev, beta, or ga (got: $VARIANT)" >&2
  exit 1
fi

if [ ! -d "icons/$VARIANT" ]; then
  echo "icons/$VARIANT not found — generating icons automatically..."
  ./scripts/generate-icons.sh
fi

echo "Applying icon variant: $VARIANT"

# ── iOS ──
IOS_DEST="app/ios-app/src/Assets.xcassets/AppIcon.appiconset"
mkdir -p "$IOS_DEST"

# Copy light + dark 1024 icons
cp "icons/${VARIANT}/ios/AppIcon-light-1024.png" "${IOS_DEST}/AppIcon.png"
cp "icons/${VARIANT}/ios/AppIcon-dark-1024.png"  "${IOS_DEST}/AppIcon-dark.png"

# Write modern Contents.json (single-size universal with dark mode)
cat > "${IOS_DEST}/Contents.json" << 'EOF'
{
  "images": [
    {
      "filename": "AppIcon.png",
      "idiom": "universal",
      "platform": "ios",
      "size": "1024x1024"
    },
    {
      "appearances": [
        {
          "appearance": "luminosity",
          "value": "dark"
        }
      ],
      "filename": "AppIcon-dark.png",
      "idiom": "universal",
      "platform": "ios",
      "size": "1024x1024"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "universal",
      "platform": "watchos",
      "size": "1024x1024"
    },
    {
      "appearances": [
        {
          "appearance": "luminosity",
          "value": "dark"
        }
      ],
      "filename": "AppIcon-dark.png",
      "idiom": "universal",
      "platform": "watchos",
      "size": "1024x1024"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "1x",
      "size": "16x16"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "2x",
      "size": "16x16"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "1x",
      "size": "32x32"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "2x",
      "size": "32x32"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "1x",
      "size": "128x128"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "2x",
      "size": "128x128"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "1x",
      "size": "256x256"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "2x",
      "size": "256x256"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "1x",
      "size": "512x512"
    },
    {
      "filename": "AppIcon.png",
      "idiom": "mac",
      "scale": "2x",
      "size": "512x512"
    }
  ],
  "info": {
    "author": "xcode",
    "version": 1
  }
}
EOF

# Remove legacy per-size PNGs (they'll be regenerated by Xcode from the 1024)
find "$IOS_DEST" -name "AppIcon-*.png" ! -name "AppIcon-dark.png" -delete 2>/dev/null || true
find "$IOS_DEST" -name "AppIcon@*.png" -delete 2>/dev/null || true
find "$IOS_DEST" -name "AppIcon~*.png" -delete 2>/dev/null || true

echo "  ✓ iOS"

# ── Android ──
ANDROID_RES="app/android-app/res"
for density in mipmap-mdpi mipmap-hdpi mipmap-xhdpi mipmap-xxhdpi mipmap-xxxhdpi mipmap-anydpi-v26; do
  mkdir -p "${ANDROID_RES}/${density}"
  cp "icons/${VARIANT}/android/${density}/"* "${ANDROID_RES}/${density}/"
done
echo "  ✓ Android"

# ── Tauri / Desktop ──
mkdir -p src-tauri/icons
cp "icons/${VARIANT}/tauri/icon.png"  src-tauri/icons/icon.png
cp "icons/${VARIANT}/tauri/icon.ico"  src-tauri/icons/icon.ico
cp "icons/${VARIANT}/tauri/icon.icns" src-tauri/icons/icon.icns
echo "  ✓ Tauri"

# ── Web ──
cp "icons/${VARIANT}/web/favicon.ico"         app/web-app/favicon.ico
cp "icons/${VARIANT}/web/apple-touch-icon.png" app/web-app/apple-touch-icon.png
echo "  ✓ Web"

# ── Shared UI onboarding logo ──
SHARED_UI_KOTLIN_DIR="app/shared-ui/src/commonMain/kotlin/finance/shilling/shared/ui"
mkdir -p "$SHARED_UI_KOTLIN_DIR"
cat > "${SHARED_UI_KOTLIN_DIR}/AppLogoAsset.kt" <<'EOF'
package finance.shilling.shared.ui

internal object AppLogoAsset {
    internal val base64Png: String = buildString {
EOF
base64 < "icons/${VARIANT}/ios/AppIcon-light-1024.png" | awk '
  {
    for (i = 1; i <= length($0); i += 4096) {
      print substr($0, i, 4096)
    }
  }
' | while IFS= read -r chunk; do
  printf '        append("%s")\n' "$chunk" >> "${SHARED_UI_KOTLIN_DIR}/AppLogoAsset.kt"
done
cat >> "${SHARED_UI_KOTLIN_DIR}/AppLogoAsset.kt" <<'EOF'
    }
}
EOF
echo "  ✓ Shared UI"

echo "Done! All platforms now use the '$VARIANT' icon variant."
